### ISSUE TITLE
Actividad 7 Juicio experto y costos

### ISSUE THREAD

**Issue by MLR062998** [SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-equipo-de-angeles#1]
[Juicio_Experto_y_costos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-juicio-experto-y-costos-equipo-de-angeles/files/13329040/Juicio_Experto_y_costos.pdf)

**Comment by JoseABCruz** [comment]
Calificación: 25%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
